### ISSUE TITLE
File Upload: Csv files not ingested when added as part of a multi file zip upload.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1907]
Testing with a collection of sample files included in testfiles.zip. There are 15 or so files of each major type. There are 3 smaller csv files that attempt to ingest when uploaded alone or with 2 or 3 files but fail to attempt to ingest when uploaded as part of the larger zip file.

I can provide the test zip file.

**Comment by landreev** [comment]
Should be working now, please re-test.

**Comment by sbarbosadataverse** [comment]
@landreev  tested as part of multi file zip upload, all but one .csv file failed ingest. If they fail with the proper message does that mean this issue is resolved?

**Comment by sbarbosadataverse** [comment]
@kcondon 
I removed the csv files that failed ingest when in "zip"--re-uploaded individually and they still failed ingest, except for the one that was successful in zip and individually.

**Comment by sbarbosadataverse** [comment]
@kcondon 
tested your zip file and only one csv file failed upload as both part of the zip and single file upload

https://dvn-build.hmdc.harvard.edu/dataset.xhtml?persistentId=doi%3A10.5072%2FFK2%2FATJZWC&version=DRAFT

**Comment by kcondon** [comment]
This is working. The failing file had a formatting issue. I corrected it and everything works as expected. Closing.
