### ISSUE TITLE
Files: Ability to Replace a File Instead of Deleting

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2290]
For the Provenance project, we need to determine how a user can replace a file instead of deleting the file and uploading a new one.

This relates to the backend structure (@scolapasta and @landreev) and what it looks like in the UI (@eaquigley and @mheppler)

---
- [ ] Make sure group check is activated before pull request!!

**Comment by djbrooke** [comment]
Notes from @raprasad from #3220

> To support Provenance, we need to add versioning/replace functionality for DataFile objects.
> 
> Basics:
> 
> User may replace an existing dataset file with a new one:
> via UI
> via API
> File versions are tied to dataset versions
> Technical notes:
> 
> Internal storage:
> 
> DataFile will have two extra fields:
> Root DataFile id
> Previous DataFile id
> DataFile id	Root DataFile ID	Previous DataFile ID
> 1	1	null
> 5	1	1
> 7	1	5
> 35	1	7

**Comment by djbrooke** [comment]
[Mockups](https://iqssharvard.mybalsamiq.com/projects/filesprovenancefacetsfilter-dataverse40/File%20-%20Versions)

**Comment by mheppler** [comment]
![file-replace-step-1](https://cloud.githubusercontent.com/assets/687227/18672986/2f9c963c-7f18-11e6-8d8c-826db7c1d739.jpg)

**Comment by raprasad** [comment]
Functionality|File Add|File Replace|Return Error Message
---|:---:|:---:|:---:
Verify user and permissions                         |Yes|Yes|Yes
Retrieve dataset                                    |Yes|Yes|Yes
Ensure file to replace exists                       |--|Yes|Yes
Send new file to ingestService.createDataFiles(..)  |Yes|Yes|Yes
Duplicate check (compare checksums)                 |Yes|Yes|Yes
Does replacement file's content type differ? (send warning message)|--|Yes|Yes
Does replacement file's extension differ (send warning message)|--|Yes|Yes
Check for contstraint violations                    |Yes|Yes|Yes
Optional.  Update Datafile description              |Yes|Yes|--
Optional.  Update Datafile tags                     |Yes|Yes|--
Optional.  Update Datafile categories               |Yes|Yes|--
Add Root Datafile Id (has to happen everywhere)     |Yes|Yes|--
Add Previous Datafile Id                            |--|Yes|--
Send new file to ingestService.addFiles(..)         |Yes|Yes|Yes
Add Replaced file to delete files list              |--|Yes|--
Create "UpdateDatasetCommand" with both new file and file to delete|--|Yes|Yes
Run command                                         |Yes|Yes|Yes
Send user notifications                             |Yes|Yes|--
Run ingestService.startIngestJobs(..)               |Yes|Yes|--

**Comment by raprasad** [comment]
main issues/tasks:
- [ ] replace: recovery from finding duplicate file in new draft
- [ ] ability to add description and tags
- [ ] tests

**Comment by djbrooke** [comment]
Closed #2157, as it will be covered by this.

**Comment by pdurbin** [comment]
@akio-sone do you think [ModeShape](http://modeshape.jboss.org) could be used in the context of "file replace"?

**Comment by djbrooke** [comment]
If they are needed in order to complete this issue, we should reflect the list of tests from #3387 as part of this issue.

**Comment by djbrooke** [comment]
Test list from #3387:

 1) 

- [ ] Add good file
- [ ] Add File null dataset id
- [ ] Add file by non-existent id dataset id
- [ ] Add good file
- [ ] Load good dataset by id
- [ ] User w/o Edit Dataset Perms
- [ ] User w/ Edit Dataset Perms
- [ ] Load new good file, name, content type
- [ ] Load null file input stream
- [ ] Load null file name
- [ ] Load null content type
- [ ] Load good file to replace by id
- [ ] Load file to replace by null id
- [ ] Load file to replace by non-existent id
- [ ] Load file to replace by id from other dataset
- [ ] Load unpublished file to replace by id
- [ ] Load deleted file to replace by id (file from previous version)

**Comment by raprasad** [comment]
mini checklist

- [ ] limit file size on API add/replace
  - This isn't completely obvious with a fileInputStream
  - For DatasetPage, param is added to the widget to limit upload size

**Comment by raprasad** [comment]
UI checklist for updating EditDatafilesPage.java and associated editFilesFragment.xhtml

- [ ] Add ```SINGLE_REPLACE``` mode
  - [ ]  Read fileToReplace from the url
- [ ] Toggle single/multiple upload
  - [ ] Native upload
  - [ ] Dropbox upload
- [ ] Alternate ```handle upload``` paths
  - [ ] Native upload
  - [ ] Dropbox upload

**Comment by raprasad** [comment]
RP note for when this branch is merged with the #3116 fixes:
![img_1725](https://cloud.githubusercontent.com/assets/1036060/20321383/42be9dc6-ab43-11e6-94aa-6183cbc16523.JPG)

**Comment by sekmiller** [comment]
With respect to editing data tags at the time of file replace, it should be noted that the data tags are only available for editing once the file has been ingested and it has been established that it is a tabular file. The data tags are not available for edit on upload because the ingest actually happens later. This also occurs on the dataset page when a tabular file is first uploaded.

**Comment by raprasad** [comment]
@sekmiller: thx for the comment, I hadn't removed that item from the original 10/14 checklist.  However, the code disallows data tags for new files.  The tests include this--e.g. trying to add data tags to non-tabular (or not-yet-recognized as tabular) files

**Comment by raprasad** [comment]
I'll clean up that checklist.  UI checklist is here:  https://github.com/IQSS/dataverse/issues/2290#issuecomment-258941659

**Comment by raprasad** [comment]
Solr question:
  - Capture ```previousdatafileid``` and ```rootdatafileid``` in the Solr schema
  - Even if unused in this release, these id's could start getting indexed 
  - Are they potentially useful in future releases?

**Comment by mheppler** [comment]
"Need success message when you replace a file", as [recommended by the UX Team](https://docs.google.com/document/d/1mNNRqRqIW92LXock332sIA-uXh-2agOpoyLLLKwXUA0/edit) based upon user feedback in usability testing of 4.6.

**Comment by djbrooke** [comment]
We discussed this in the planning meeting on 1/4. The following items remain:

- [ ] Fix messages not displaying in certain situations
- [ ] Resolve merge conflicts introduced by the file page
- [ ] Verify that the REST assured tests are still passing, fix those that are not
- [ ] Lingering UI issues
- [ ] Documentation

**Comment by mheppler** [comment]
An additional remaining item that @sekmiller and I discussed today:

- [ ] The dataset Version Details for "Files (Replaced: {#})" need to be wired up

**Comment by landreev** [comment]
omg, figured it out finally - why the page was having all the refresh issues in file replace mode. 
will commit shortly and send some details.

**Comment by raprasad** [comment]
don't keep us in some suspense too long...

**Comment by landreev** [comment]
@raprasad , @sekmiller 
I believe I have fixed that issue where you could not replace a published file when there was an already-existing draft version of the dataset.
If you have a sec, could you at some point verify that the all this replace business is working properly now. In case I missed something; this stuff is still relatively new to me.

**Comment by landreev** [comment]
Thanks @pdurbin for fixing the REST Assuered test.

**Comment by raprasad** [comment]
fyi: am running the 2290 branch and getting errors when attempting to delete multiple files from a draft:
```
Caused by: java.lang.IllegalArgumentException: Cannot merge an entity that has been removed: edu.harvard.iq.dvn.core.study.FileMetadata[id=748]
```

**Comment by raprasad** [comment]
don't take above comment too seriously--may have been a local DV in a bad state

**Comment by dlmurphy** [comment]
While writing documentation for File Replace I noticed something I think is a bug.  

On the Replace File page, after uploading a replacement file I decided to delete the replacement using the Delete button. The warning box says that I'll need to click the Save Changes button on the following page in order to delete the file:

![delete file box](https://cloud.githubusercontent.com/assets/22962740/21781857/4016e558-d67f-11e6-9489-565cb433c10a.PNG)


However, when I click Continue, on the following page I get a success message telling me that the replacement file has been deleted _before_ I've hit the Save Changes button. Additionally, I am unable to upload a new replacement because the "Select Files to Add" button is grayed out.

![file replace bug](https://cloud.githubusercontent.com/assets/22962740/21781772/e7c2b954-d67e-11e6-9575-3d804259eace.PNG)

When I then click Save Changes, I get the following error message:

![file replace bug 3](https://cloud.githubusercontent.com/assets/22962740/21811666/81e74e10-d71e-11e6-82d3-9efab426ff67.PNG)

After this message, _then_ I'm allowed to add a new file.

**Comment by mheppler** [comment]
- [ ] 500 error: when replacing replacement file, add dialog msg, create new issue for other development
- [ ] Bug: upload widget disabled after delete file on replace-upload
- [ ] Messaging
- [ ] Default icon/thumbnail preview
- [ ] Restricted icon
- [ ] Dataset Version Details for **"Files (Replaced: {#})"**
- [ ] User Guide

**Comment by pdurbin** [comment]
These days I'm deploying this code to https://dev1.dataverse.org if anyone would like to check it out. Newly written docs are linked from that server as well.

**Comment by landreev** [comment]
There was some discussion about error messages in file replace, specifically about duplicate file errors. There was one thing I noticed there: there was a separate method for detecting whether the user was attempting to replace a file with the exact same file; BUT it was always called AFTER the main duplicate check. So the condition would never get detected. Because it would always be caught first as simply an attempt to replace a file with a file already in the dataset... 

So I just reversed the order of these checks; and you should now be seeing separate error messages for "can't replace the file with the exact same file" and "file already in the dataset".

**Comment by pdurbin** [comment]
I've been fixing bug here and there, especially for #1612 but as of yesterday morning when I merged the latest from develop into pull request #3579 I'm done messing with the branch. Since then @kcondon has been QA'ing it. I'm unassigning myself from this issue.

**Comment by kcondon** [comment]
Issues:
1. On file landing page for replaced file, edit button still appears, including the replace option which is not possible. Choosing any option results in an error since there is no current version for this file.
2. Replacing a file with a different type in the UI should give the user an opportunity to not do so by presenting a popup with the info of different types. Currently just replaces with a message.
3. Minor wording issue in error response in API when trying to replace a file with a different type without force option.
4. Force option in file replace api endpoint that allows replacing a file with a different type is not documented

**Comment by landreev** [comment]
> 6. API add/replace code ignores file size upload limit. Leonid knows something about this.

Ok, yes, I effectively disabled the size limit check in Raman's API upload/replace framework when I was merging his code in. 
Just went ahead and fixed it; please re-test.
