### ISSUE TITLE
Metrics icon

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#2502]
The "Metrics" icon has a prominent place at the top of the page but 3 of the 4 metrics (all but "Downloads", which does look great) say "Coming soon..." For now, should we simply remove "Coming soon..." (added in #1952) or consider removing the "Metrics" icon (and moving the "Downloads" number)?

![views](https://cloud.githubusercontent.com/assets/21006/9798601/fd0363b0-57cf-11e5-8d05-969de6b5a424.png)

![downloads](https://cloud.githubusercontent.com/assets/21006/9798606/02cf0182-57d0-11e5-9faa-ac0c722fbcfc.png)

![citations](https://cloud.githubusercontent.com/assets/21006/9798612/0db02356-57d0-11e5-9d34-d1501046614d.png)

![shares](https://cloud.githubusercontent.com/assets/21006/9798610/077cd826-57d0-11e5-9b77-3393ce04ddb5.png)

**Comment by mheppler** [comment]
- [ ] Disable the hover/toggle functionality, hiding the "Coming soon..." sections until they're ready to be developed.

**Comment by mheppler** [comment]
Disabled hover-toggle functionality from the Metrics block on the dataverse, dataset, file pages in order to hide "Coming soon..." text.

Committed changes to a new branch titled "2016-01-ux-branch". This is branch is not associated with a milestone, which is why none is selected for this ticket.

**Comment by pdurbin** [comment]
I just merged this into the 4.3 branch per my comment at https://github.com/IQSS/dataverse/issues/2852#issuecomment-170628537

**Comment by pdurbin** [comment]
The "develop" branch was created from 4.3 so this fix is already in develop.

**Comment by kcondon** [comment]
@mheppler @pdurbin This is still happening on dvn-build, built from develop. Phil, this is now in develop branch, right?

**Comment by pdurbin** [comment]
Yep. Already in develop.

**Comment by kcondon** [comment]
OK but not working.

**Comment by mheppler** [comment]
I tested this again in dvn-build, as well as my local dev environment of the "develop" branch. Both environments show that the "hover-toggle" functionality of the Metrics widget has been disabled, so that when you mouse over the blue, burnt-orange and orange blocks at the bottom of the widget, the larger color-block above them remains on the green "Downloads" section.

If this "hover-toggle" functionality is still being seen in an environment running the "develop" branch, it is most likely because the browser you are using has a cached version of the JS file that I edited in my commit 7a3a630ef381604cfdd609702dda193a8a5d5858.

To clear this cached file from the browser, hold the "shift" key while you click the "refresh" button on your browser window. This will pull a new version of all cached files from the server. You should then see the new functionality. If not, pass this back to me with more details about the server, the browser and other details that I might need to replicate.

**Comment by kcondon** [comment]
OK, I had done shift+refresh but maybe I clicked on the tab which causes coming soon to appear. I understand this ticket is about hover only not removing click through. Closing.

**Comment by mheppler** [comment]
My apologies. Didn't realize that there was a "click" action that needed to be disbled as well. I am reopening this ticket to fix.

**Comment by mheppler** [comment]
Disable click-toggle functionality of the Metrics block on the dataverse, dataset and file pages.

This code commit was made to the ["feb-16-ux-fixes"](https://github.com/IQSS/dataverse/tree/feb-16-ux-fixes) branch and can be tested there. Sorry for the mixup regarding the hover vs. click functionalities. Should have caught that on the first pass.

**Comment by kcondon** [comment]
OK, hover and clicks are disabled. Closing.
