### ISSUE TITLE
Refine HTTP response code for bad API tokens

### ISSUE THREAD

**Issue by michbarsinai** [IQSS/dataverse#3250]
Currently we reply with `unauthorized`. Should really be `400 bad request`.

**Comment by pdurbin** [comment]
Not `403 Forbidden`? What's driving this change? I guess I don't understand the context of this issue.

**Comment by michbarsinai** [comment]
Differentiating between an incorrect/invalid token and an OK token that's not authorized to access a resource.

**Comment by pdurbin** [comment]
I see. Well, this will likely break a lot of tests at https://build.hmdc.harvard.edu:8443/job/phoenix.dataverse.org-apitest-develop/ . Also, I'm changing the title of this issue from "HTML" to "HTTP" since that's what I think is meant.

**Comment by pdurbin** [comment]
@michbarsinai has this been addressed in pull request #3381? If so, can you please associate this issue with that pull request and move it into QA? I'll put this in Code Review with your name on it at https://waffle.io/IQSS/dataverse so we're sure to figure this out before the pull request is completely tested and merged.

**Comment by kcondon** [comment]
This is not fixed as part of the 3358 pull request. Still returns a 401 Unauthorized. Passing back to Michael.

**Comment by pdurbin** [comment]
@michbarsinai do you still want this?

**Comment by michbarsinai** [comment]
No, I think we're good.

**Comment by pdurbin** [comment]
Ok, closing. Thanks. If anyone out there still wants this or something similar, please open a new issue.
