### ISSUE TITLE
Documentation: Guides have broken github icons in the footer.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3388]
All guides in documentation have broken github icons in the footer:
This has happened before, was working in 4.4, broken in 4.5, must use browser like Chrome to see broken image, FF hides it.

**Comment by mheppler** [comment]
Possibly a symptom related to issue #3181. Will investigate locally.

**Comment by mheppler** [comment]
Fixed URL ref to githubicon.png which was displaying as a broken img in the guides footer. Resized image file (512px) to be smaller (96px).

Code checked into the [3181-guides-build-warning](https://github.com/IQSS/dataverse/tree/3181-guides-build-warning) branch.

**Comment by mheppler** [comment]
Made copyright year in guides footer dynamic. d8f1b98a6776c25b79312e44f1e6ea7baa24a1e0

**Comment by kcondon** [comment]
The icons are fixed but cannot test the footer date since I cannot adjust the system date on the build machine @mheppler @pdurbin please test on your dev boxes thanks.

**Comment by mheppler** [comment]
With the direction of @pdurbin, fudged date to test copyright locally.

![screen shot 2020-09-29 at 4 35 10 pm](https://cloud.githubusercontent.com/assets/687227/18971401/ee749bee-8662-11e6-87c3-d9a5ce2b9598.png)

**Comment by pdurbin** [comment]
Still broken as of 9f93e7b on the homepage for the docs at least.

**Comment by pdurbin** [comment]
I'm proposing a fix in 74d6846 (pull request #3394) that uses an absolute rather than relative path. It relies on the fact that we create a symlink called "latest". That is to say the GitHub icon is at http://guides.dataverse.org/en/latest/_static/images/githubicon.png . Passing to QA.
